function itpINFO = itp_import_profiler_loc(filename)
%itp_import_profiler_loc Import numeric data from a text file as a matrix.
%   itpINFO = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
% Example:
%   itp110grd0012 = importfile('itp110grd0012.dat');
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/01/30 13:32:57

%% Initialize variables.
startRow = 2;
endRow = 2;


%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%5f%10f%10f%10f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Create output variable
dataArray = cellfun(@(x) num2cell(x), dataArray, 'UniformOutput', false);
data = [dataArray{1:end-1}];

% manually assign to output matrix --- this method is 10x faster than
% reading as a table or as strings
itpINFO.year = data{1};
itpINFO.day = data{2};
itpINFO.lon = data{3};
itpINFO.lat = data{4};
itpINFO.obs = data{5};
end



