function [pressure, temperature, salinity, numObs] = itp_import_profiler_data(filename,status)
%IMPORTFILE Import data from a text file
%  [PRESSURE, TEMPERATURE, SALINITY, NUMOBS] = IMPORTFILE(FILENAME,status)
%  reads data from text file FILENAME and uses STATUS to differentiate
%  between grddata and final file formats.
%  Returns the data as column vectors.
%
% Auto-generated by MATLAB on 31-Jan-2021 13:28:16

%% tier 3 data is FINAL
if status == 3
    %% Input handling
    dataLines = [4, Inf];
    
    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 4);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = " ";
    
    % Specify column names and types
    opts.VariableNames = ["pressure", "temperature", "salinity", "numObs"];
    opts.SelectedVariableNames = ["pressure", "temperature", "salinity", "numObs"];
    opts.VariableTypes = ["double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.ConsecutiveDelimitersRule = "join";
    opts.LeadingDelimitersRule = "ignore";
    
    % Import the data
    tbl = readtable(filename, opts);
    
    %% Convert to output type
    pressure = tbl.pressure;
    
    if mean(pressure,'omitnan') > 2000
        warning('changing file status for %s',filename)
        status = 2;
    end
    temperature = tbl.temperature;
    salinity = tbl.salinity;
    numObs = tbl.numObs;
end  
%% tier 2 data = grddata
if status == 2
    %% Input handling
    dataLines = [4, Inf];
    
    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 5);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = " ";
    
    % Specify column names and types
    opts.VariableNames = ["Var1", "Var2", "pressure", "temperature", "salinity"];
    opts.SelectedVariableNames = ["pressure", "temperature", "salinity"];
    opts.VariableTypes = ["string", "string", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.ConsecutiveDelimitersRule = "join";
    opts.LeadingDelimitersRule = "ignore";
    
    % Specify variable properties
    opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");
    
    % Import the data
    tbl = readtable(filename, opts);
    
    %% Convert to output type
    pressure = tbl.pressure;
    temperature = tbl.temperature;
    salinity = tbl.salinity;
    numObs = NaN;
end
end